[features]
resolution = true
skip-lint = false

[programs.localnet]
auctioning = "3GGYRVymmKQhmxP9nw9yPs8HCf7YWw7WViPjkKFkZNGs"

[programs.devnet]
auctioning = "3GGYRVymmKQhmxP9nw9yPs8HCf7YWw7WViPjkKFkZNGs"

[programs.mainnet]
# sync after redeploy
auctioning = "3GGYRVymmKQhmxP9nw9yPs8HCf7YWw7WViPjkKFkZNGs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p auctioning"
