[features]
seeds = false
skip-lint = false

[programs.localnet]
auctioning = "3GGYRVymmKQhmxP9nw9yPs8HCf7YWw7WViPjkKFkZNGs"

[programs.devnet]
auctioning = "3GGYRVymmKQhmxP9nw9yPs8HCf7YWw7WViPjkKFkZNGs"

[programs.mainnet]
# sync after redeploy
auctioning = "3GGYRVymmKQhmxP9nw9yPs8HCf7YWw7WViPjkKFkZNGs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.mainnet-beta.solana.com"
# For local testing you can use `solana-test-validator` or MagicBlock local ER.
