[package]
name = "auctioning"
version = "0.1.0"
description = "auctioning.lol — public RP ledger on Solana mainnet"
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version = "1.86"

[lib]
crate-type = ["cdylib", "lib"]
name = "auctioning"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "1.1", features = ["init-if-needed"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("anchor-debug", "custom-heap", "custom-panic", "no-log-ix-name", "solana"))',
] }

[dev-dependencies]
borsh = "1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
